<a href="https://colab.research.google.com/github/mkap007/Python_For_Geospatial_Analysis/blob/main/calculator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

# Create two random 4*4 matrices
matrix1 = np.random.rand(4, 4)
matrix2 = np.random.rand(4, 4)

# Display basic properties of the matrices
print("Matrix 1:")
print(matrix1)
print("Shape:", matrix1.shape)
print("Size:", matrix1.size)
print("Data type:", matrix1.dtype)
print("Dimension:", matrix1.ndim)
print()

print("Matrix 2:")
print(matrix2)
print("Shape:", matrix2.shape)
print("Size:", matrix2.size)
print("Data type:", matrix2.dtype)
print("Dimension:", matrix1.ndim)


Matrix 1:
[[0.36671563 0.5528139  0.11157644 0.11588894]
 [0.03775789 0.56187687 0.20046476 0.54334842]
 [0.4990758  0.14971755 0.13615209 0.6486536 ]
 [0.83521751 0.70090608 0.41210014 0.90477482]]
Shape: (4, 4)
Size: 16
Data type: float64
Dimension: 2

Matrix 2:
[[0.25446588 0.45646466 0.2085455  0.83385843]
 [0.34848023 0.83166182 0.63055365 0.98619306]
 [0.55696541 0.90221639 0.93378661 0.5191443 ]
 [0.23011255 0.21812683 0.37530017 0.13582681]]
Shape: (4, 4)
Size: 16
Data type: float64
Dimension: 2


In [2]:
# Addition
add = np.add(matrix1, matrix2)
print("Matrix 1 + Matrix 2:")
print(add)
print()

# Subtraction
sub = np.subtract(matrix1, matrix2)
print("Matrix 1 - Matrix 2:")
print(sub)
print()

# Multiplication
mul = np.multiply(matrix1, matrix2)
print("Matrix 1 * Matrix 2:")
print(mul)
print()

# Division
div = np.divide(matrix1, matrix2)
print("Matrix 1 / Matrix 2:")
print(div)
print()

Matrix 1 + Matrix 2:
[[0.6262961  0.39157131 0.24950556 1.19547496]
 [1.1180277  1.21767367 0.27234735 0.96693968]
 [0.43412747 0.94982717 1.02880143 0.84580033]
 [0.90069105 0.177343   1.26642041 0.55808044]]

Matrix 1 - Matrix 2:
[[-0.57856147  0.28547979  0.20605446 -0.10132335]
 [-0.83637383  0.09595965 -0.04290915 -0.95350008]
 [-0.34244778  0.88542353  0.75966927 -0.21268057]
 [-0.107937    0.09610702  0.41808507 -0.03467362]]

Matrix 1 * Matrix 2:
[[0.01437835 0.01795735 0.00494865 0.35472349]
 [0.13761619 0.36838023 0.01808297 0.00645248]
 [0.01779905 0.02954921 0.12033374 0.16753629]
 [0.19989849 0.0055535  0.35725638 0.07756288]]

Matrix 1 / Matrix 2:
[[3.96184764e-02 6.38176427e+00 1.04844297e+01 8.43733062e-01]
 [1.44112591e-01 1.17109468e+00 7.27782615e-01 6.99818759e-03]
 [1.18056418e-01 2.84960716e+01 6.64532522e+00 5.98139994e-01]
 [7.85972639e-01 3.36611968e+00 1.98565991e+00 8.83008398e-01]]



In [24]:
def user_matrix():
  rows = int (input("\nEnter the Numbers of Rows: "))
  cols= int (input("\nEnter the Number of Columns: "))

  mtrx = []
  for i in range (rows):
   row = []
   for j in range (cols):
     elements = float(input(f"\nEnter the Elemets at Row {i+1} and Column {j+1}:"))
     row.append(elements)

   mtrx.append(row)
  mtrx = np.array(mtrx)
  return mtrx

def cal (mtrx1, mtrx2):
  operations = input ("\nWrite/Enter the Type of Operation you want to Perform (addition, substraction, multiplication, or division): ")
  if operations == "addition":
    result = np.add(mtrx1, mtrx2)
  elif operations == "substraction":
    result = np.subtract(mtrx1, mtrx2)
  elif operations == "multiplication":
    result = np.multiply(mtrx1, mtrx2)
  elif operations == "division":
    result = np.divide(mtrx1, mtrx2)
  else:
    print("\nInvalid Operation, Please write the correct Spelling. Please Enter one of the Following: addition, substraction, multiplication, or division.")
    return None
  return result

def user():
  choice = input("\nDo you want to Input the Matrix values or Create Random Matrices ? (Type: input or random): ")
  if choice == "input":
    print("\nCreate the First Matrix: ")
    mtrx1 = user_matrix()
    print("Create the Second Matrix: ")
    mtrx2 = user_matrix()
  elif choice == "random":
    rows = int(input("\nEnter the Number of Rows for the Random Matrices: "))
    cols  = int(input("\nEnter the Number of Columns for the Random Matrices: "))

    mtrx1 = np.random.rand(rows, cols)
    mtrx2 = np.random.rand(rows, cols)
  else:
    print("\nInvalid Choice, Please Write one of the Following: input or random.")
    return

  print("Matrix 1: ", mtrx1)
  print()

  print("Matrix 2: ", mtrx2)
  print()


  result = cal(mtrx1, mtrx2)
  if result is not None:
    print("Result: ", result)
    print()

  another = input("\nDo you want to Perform another Operation ? (Type: yes or no): ")
  if another == "yes":
    user()
  elif another == "no":
    print("\nThank You for using The Matrix Calculator. Have a Great Day!😊")
  else:
    print("\nInvalid Answer. Please Enter one of the Following options: yes or no.")

user()



Do you want to Input the Matrix values or Create Random Matrices ? (Type: input or random): input

Create the First Matrix: 

Enter the Numbers of Rows: 2

Enter the Number of Columns: 2

Enter the Elemets at Row 1 and Column 1:12

Enter the Elemets at Row 1 and Column 2:23

Enter the Elemets at Row 2 and Column 1:21

Enter the Elemets at Row 2 and Column 2:32

Create the Second Matrix: 

Enter the Numbers of Rows: 2

Enter the Number of Columns: 2

Enter the Elemets at Row 1 and Column 1:9

Enter the Elemets at Row 1 and Column 2:8

Enter the Elemets at Row 2 and Column 1:8

Enter the Elemets at Row 2 and Column 2:9
Matrix 1:  [[12. 23.]
 [21. 32.]]

Matrix 2:  [[9. 8.]
 [8. 9.]]


Write/Enter the Type of Operation you want to Perform (addition, substraction, multiplication, or division): substraction
Result:  [[ 3. 15.]
 [13. 23.]]


Do you want to Perform another Operation ? (Type: yes or no): no

Thank You for using The Matrix Calculator. Have a Great Day!😊
