<a href="https://colab.research.google.com/github/mkap007/Python_For_Geospatial_Analysis/blob/main/Numpy_assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1><b>Batch 1- Python for Geospatial Data Analysis ( Assignment No 2)</b></h1>

**1. Create Array Using Python List .[2, 4, 6, 8]**

In [1]:
import numpy as np

In [2]:
l1 = [2,4,6,8]
arrl1 = np.array(l1)

print(arrl1)

[2 4 6 8]


**2. Create An Array by Directly Passing element**

In [3]:
darr = np.array([2,3,4,5,6,7,8,9])
print(darr)

[2 3 4 5 6 7 8 9]


**3. Create an array with 4 elements filled with zeros**

In [4]:
zerray = np.zeros(4)
print(zerray)

[0. 0. 0. 0.]


**4. Create an array filled with values 1**

In [5]:
onarrr = np.ones(5)
print(onarrr)

[1. 1. 1. 1. 1.]


**5. Create an array with values from 0 to 4.**

In [6]:
valarr = np.array([0,1,2,3,4])

valarr1 = np.arange(5)

print(valarr1)

[0 1 2 3 4]


**6. Create an array with values from 1 to 8 with a step of 2**

In [7]:
rarry = np.arange(1,9,2)
print(rarry)

[1 3 5 7]


**7. Generate an array of 5 random numbers.**

In [8]:
rnd = np.random.rand(5)
print(rnd)

[0.55031336 0.44996339 0.40409506 0.78454454 0.40288325]


**8. Create an empty array of length 4.**

In [9]:
mpty = np.empty(4)
print(mpty)

[5.07029665e-310 0.00000000e+000 6.83246574e-310 6.83245531e-310]


**9. Create a 2D array with 2 rows and 4 columns.**

In [10]:
Twod = np.array([[1,2,3,4], [5,6,7,8]])
print(Twod)

[[1 2 3 4]
 [5 6 7 8]]


**10. create an empty 2D array with 2 rows and 2 columns**

In [11]:
mpty2d = np.empty((2,2))
print(mpty2d)

[[5.07029665e-310 0.00000000e+000]
 [6.83246574e-310 6.83245531e-310]]


**11. create a 2D array of 2 rows and 2 columns of random numbers**

In [12]:
rnd2d = np.random.rand(2,2)
print(rnd2d)

[[0.35221684 0.39007904]
 [0.28374699 0.56353837]]


**12. Create a 2-D array with elements initialized to 5**

In [13]:
iniarr = np.full((2,2),5)
print(iniarr)

[[5 5]
 [5 5]]


**13. Create an array of integers, floating Points, Complex Number.**

In [14]:
mixarr = np.array([23, 3.4, 45j])
print(mixarr)

[23.  +0.j  3.4 +0.j  0. +45.j]


**14. Define Two Array Perform Following Operation Using For Loop**
  1. Addition
  2. Subtraction
  3. Multiplication
  4. Division

In [15]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

addition = np.empty(4)
subtraction = np.empty(4)
multiplication = np.empty(4)
division = np.empty(4)

for i in range(4):

  addition[i] = array1[i] + array2[i]
  subtraction[i] = array1[i] - array2[i]
  multiplication[i] = array1[i] * array2[i]
  division[i] = array1[i] / array2[i]

print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)


Addition: [ 6.  8. 10. 12.]
Subtraction: [-4. -4. -4. -4.]
Multiplication: [ 5. 12. 21. 32.]
Division: [0.2        0.33333333 0.42857143 0.5       ]
